# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cat_server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61t_server.proto\x12\x08\x63\x61t_fact\"\x0e\n\x0c\x45mptyRequest\"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2K\n\x0e\x43\x61tFactService\x12\x39\n\x0bGetResponse\x12\x16.cat_fact.EmptyRequest\x1a\x12.cat_fact.ResponseB\x0cZ\n./cat_factb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cat_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n./cat_fact'
  _globals['_EMPTYREQUEST']._serialized_start=30
  _globals['_EMPTYREQUEST']._serialized_end=44
  _globals['_RESPONSE']._serialized_start=46
  _globals['_RESPONSE']._serialized_end=73
  _globals['_CATFACTSERVICE']._serialized_start=75
  _globals['_CATFACTSERVICE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
